---
- name: Create network
  docker_network:
    driver: bridge
    name: "{{ mailhog_network }}"

- name: Run mailhog mail server
  docker_container:
    image: "{{ mailhog_image }}"
    labels:
      traefik.backend: mailhog
      traefik.frontend.rule: "Host:{{ mailhog_hostname }}"
      traefik.port: "8025"
    name: mailhog
    networks:
      - name: "{{ mailhog_network }}"
    ports:
      - 1025:1025
      - 8025:8025
    recreate: true
    restart_policy: always
    state: started
